# Generated by Django 2.2.7 on 2019-12-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='paid_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='parkingticket',
            name='payment_option',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
